### ISSUE TITLE
Effector react: unmounted component 

### ISSUE THREAD

**Issue by mendrik** [effector/effector#574]
**What is the current behavior:**

I'm getting a react error while modifying a store value on fx.done

  | printWarning | @ | react-dom.development.js:67
-- | -- | -- | --
  | error | @ | react-dom.development.js:43
  | warnAboutUpdateOnUnmountedFiberInDEV | @ | react-dom.development.js:23914
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21840
  | dispatchAction | @ | react-dom.development.js:16139
  | o2 | @ | apiBase.ts:131
  | (anonymous) | @ | apiBase.ts:102
  | fn | @ | createWatch.ts:8
  | et | @ | kernel.ts:526
  | o | @ | kernel.ts:389
  | create | @ | createUnit.ts:151
  | r2 | @ | createUnit.ts:142
  | onFocus | @ | VisualNode.tsx:59

**What is the expected behavior:**

is that a problem with resolving promises in unmounted components? Since I don't use useEffect myself this seems like a bug in the library

"effector": "22.1.2",
"effector-react": "22.0.5"

**Comment by zerobias** [comment]
could you share an example online please? either in [our repl](https://share.effector.dev) or [codesandbox](https://codesandbox.io)

**Comment by mendrik** [comment]
this is gonna be tricky, because I have a complex app with all sorts of setups in react, so not sure how to replicate this to a small example. We could have a screen sharing chat if that would help :)

**Comment by doasync** [comment]
From the description it is not clear what kind of error you have and what code could lead to it.

**Comment by mendrik** [comment]
Hi, I have no changed to .watch code I had to use sample() and the bug has disappeared. I will close this, until it comes back. Otherwise I would put it under wrong usage of the framework.

**Comment by AlexandrHoroshih** [comment]
Can you share the error message?

Is this something like this?
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

(If yes, then you might want to look at this discussion in `reactwg` repo https://github.com/reactwg/react-18/discussions/82)

**Comment by mendrik** [comment]
![image](https://user-images.githubusercontent.com/160805/145201178-b6ce757e-b1a4-4749-be46-99b2da6bdf55.png)
ye it is

**Comment by mendrik** [comment]
I might have closed this prematurely, still getting the bug, but what worries me is that in my flow of affected components I have no useState() or useEffect() at work and yet I'm getting this error from apiBase.ts:131

**Comment by zerobias** [comment]
Thanks for mentioning exact line of code, now I clearly see why this happened. That behavior could be improved on our side

**Comment by zerobias** [comment]
@mendrik should be fixed in effector-react 22.0.6

**Comment by mendrik** [comment]
awesome, thank you!

**Comment by mendrik** [comment]
uff, just tested it `inc && refState.active && inc()` still gives the warning

**Comment by mendrik** [comment]
I tested it some more, and i'm still getting it at `inc && refState.active && inc()`

**Comment by zerobias** [comment]
Damn, then it happens on the react side, don’t know how we would manage that, at least without explicit reproduction
